server {
    listen 80;
    server_name localhost;

    # Directorio donde Angular compila los archivos estáticos
    root /usr/share/nginx/html;
    index index.html;

    # Soporte para el enrutamiento de Angular (evita el error 404 al recargar página)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 🚀 REVERSE PROXY: Redirige las peticiones de /api hacia el contenedor de Express
    location /api/ {
        proxy_pass http://sgo-backend:3000/; # Nombre del servicio en el docker-compose
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Manejo de errores comunes
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}