name: "SGO: Versionamiento y Release"
run-name: "Despliegue de @${{ github.actor }} en ${{ github.ref_name }}"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: "Generar Nueva Versión"
    runs-on: ubuntu-latest
    steps:
      - name: "Clonando el Repositorio"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Configurando Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: "Instalando Dependencias"
        run: npm install

      - name: "Ejecutando Semantic Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release